### ISSUE TITLE
GC MySQL 8 instance returns uppercase field names for information_schema

### ISSUE THREAD

**Issue by mzronek** [codemariner/schemart#1]
Thank you for your great work on this project. I've tried a couple of mysql schema typescript generators and this is the most promising. :)

After setup I encountered the following error: _TypeError: Cannot read properties of undefined (reading 'toUpperCase')_

I debugged the issue and it turns out that our Google Cloud MySQL Instance returns all field names queried from information_schema in uppercase (TABLE_NAME, TABLE_TYPE, COLUMN_NAME, ...) while the code needs it lowercase to work (table_name, ...).

![image](https://user-images.githubusercontent.com/3847700/224962075-0428e6f0-20c5-4a43-91c1-380a8035c25c.png)

If I can be of further assistance, please let me know.

**Comment by codemariner** [comment]
@mzronek oh dang. Thanks for bringing that to my attention. I can put up a patch soon, unless you’d rather.

**Comment by mzronek** [comment]
How do you propse to solve it? I checked for general mysql connection properties that might influence this, but couldn't find anything.

To solve it in code, I guess we have two options:

1. Lowercase all properties returned by the information_schema queries
2. Try upper- and lowercase like this: `tableName = 'table_name' in row ? row.table_name : row.TABLE_NAME;`

2 feels hacky though. No idea if some SQL server flavor might also provide us TaBlE_nAmE.

**Comment by codemariner** [comment]
@mzronek I think we should be able to modify the query to make it more specific like
```sql
        SELECT table_name as 'tableName',
               table_type as 'tableType'
...
```

let me try spinning up mysql8. I tried it initially and I remember it was kind of a pita with auth somehow, though I don't quite remember. I'll at least try it locally.

**Comment by codemariner** [comment]
@mzronek published a [patch release](https://www.npmjs.com/package/schemart/v/1.3.1) for the fix. Changes in the [this commit](https://github.com/codemariner/schemart/commit/7bba82a1db9bd206934b41b8713b53c7a999f06f).  Please let me know if that doesn't work for you. I tried it against a mysql8 instance and it seemed to work.

**Comment by mzronek** [comment]
Great solution using the case-insensitive column names of sql itself.

I have verified that 1.3.1 works properly with a GC MySQL 8 instance. Thank you for the fast patch!
